insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (1, 'Beer', 158, 0.4, 0, 3.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (2, 'Hen', 212, 18.7, 15, 0.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (3, 'Pork', 410, 12.5, 40, 12.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (4, 'Potato', 81, 2, 0.1, 18.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (5, 'Lettuce', 12, 1.3, 0.3, 2.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (6, 'Milk', 33, 3.4, 0.1, 4.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (7, 'Eggs', 157, 12.3, 11.7, 0.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (8, 'Potatoes crips', 537, 5.9, 38, 52.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (9, 'Bread', 276, 7.9, 4.5, 51.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (10, 'Chocolate dark', 570, 6.7, 34.3, 56.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (11, 'Chocolate milk', 565, 9.8, 32.8, 54.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (12, 'Lamb', 241, 14.5, 20.3, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (13, 'Duck', 310, 13.5, 28.4, 0.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (14, 'Goose', 368, 14.6, 34.3, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (15, 'Turkey', 127, 17.5, 6.2, 0.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (16, 'Beef', 229, 18.3, 17.1, 0.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (17, 'Rabbit', 162, 19.6, 9.1, 0.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (18, 'Reindeer', 123, 21, 4, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (19, 'Apricot', 49, 0.8, 0.2, 12);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (20, 'Gooseberry', 34, 0.8, 0.2, 9.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (21, 'Pineapple', 52, 0.5, 0.2, 12.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (22, 'Orange', 43, 0.8, 0.2, 11);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (23, 'Watermelon', 27, 0.7, 0.2, 6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (24, 'Raspberry', 38, 1.2, 0.6, 12.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (25, 'Avocado', 224, 1.9, 23.5, 6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (26, 'Banana', 97, 1.2, 0.3, 23.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (27, 'Strawberry', 41, 0.9, 0.4, 9.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (28, 'Lemon', 31, 0.7, 0.4, 9.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (29, 'Blackberries', 42, 1.4, 1, 12.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (30, 'Grapefruit', 38, 0.6, 0.2, 10);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (31, 'Blackcurrant', 52, 1.2, 0.3, 17.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (32, 'Kiwi fruit', 56, 1, 0.6, 13.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (33, 'Pear', 52, 0.4, 0.3, 13.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (34, 'Mandarin', 38, 0.7, 0.3, 9.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (35, 'Mango', 70, 0.6, 0.5, 16.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (36, 'Blueberry', 44, 0.7, 0.6, 11.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (37, 'Melon', 32, 0.7, 0.1, 7.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (38, 'Apple', 53, 0.4, 0.4, 13);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (39, 'Peach', 47, 0.8, 0.2, 12.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (40, 'Plum', 57, 0.7, 0.2, 14.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (41, 'Cranberry', 43, 0.4, 0.7, 9.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (42, 'Sweet cherry', 60, 0.9, 0.4, 14.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (43, 'Grapes', 69, 0.7, 0.4, 17.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (44, 'Sour cherry', 51, 1, 0.6, 12.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (45, 'Raisin', 280, 2.7, 0.6, 71.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (46, 'Sugar', 395, 0, 0, 99.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (47, 'Honey', 324, 0.3, 0, 81.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (48, 'Bean', 290, 22.8, 1.6, 60);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (49, 'Soya bean', 396, 37, 19, 32.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (50, 'Pea', 70, 6.4, 0.4, 17);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (51, 'Cucumber', 11, 0.8, 0.2, 2.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (52, 'Aubergine', 24, 1.2, 0.2, 6.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (53, 'Brussels sprout', 30, 4.3, 0.5, 6.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (54, 'Broccoli', 29, 3, 0.4, 5.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (55, 'Beetroot', 37, 1.6, 0.1, 9.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (56, 'Squash', 16, 1, 0.1, 3.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (57, 'Garlic', 128, 6.2, 0.3, 28);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (58, 'Cabbage red', 19, 1.5, 0.2, 5.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (59, 'Cabbage white', 22, 1.5, 0.2, 5.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (60, 'Dill', 31, 2.3, 0.4, 7.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (61, 'Horseradish', 61, 2.6, 0.3, 18.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (62, 'Sweetcorn', 94, 3.7, 1.6, 19.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (63, 'Carrot', 31, 1, 0.2, 8.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (64, 'Pepper�', 29, 1.3, 0.5, 6.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (65, 'Parsley leaves', 35, 4.2, 0.4, 9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (66, 'Parsley root', 39, 2.6, 0.5, 9.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (67, 'Tomato', 17, 1, 0.2, 4.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (68, 'Leek', 30, 2.2, 0.3, 6.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (69, 'Rhubarb', 9, 1.1, 0.1, 4.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (70, 'Radish', 16, 1, 0.1, 4.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (71, 'Turnip', 26, 1.1, 0.3, 8.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (72, 'Sorrel', 21, 1.1, 0.8, 4.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (73, 'Onion', 35, 1.4, 0.3, 8.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (74, 'Spinach', 19, 2.5, 0.4, 3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (75, 'Cauliflower', 20, 2.5, 0.3, 4.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (76, 'Sour milk', 61, 3.3, 3.2, 4.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (77, 'Quark', 99, 19.8, 0.5, 3.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (78, 'Liqueur', 313, 0, 0, 31);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (79, 'Vodka', 225, 0, 0, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (80, 'Wine white', 68, 0.1, 0, 0.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (81, 'Wine red', 80, 0.1, 0, 2.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (82, 'Champagne', 77, 0.3, 0, 1.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (83, 'Pineapple juice', 50, 0.3, 0.1, 11.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (84, 'Orange juice', 45, 0.6, 0.1, 9.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (85, 'Grapefruit juice', 42, 0.5, 0.1, 9.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (86, 'Carrot juice', 45, 0.4, 0.1, 11.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (87, 'Apple juice', 44, 0.1, 0.1, 10);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (88, 'Tomato juice', 14, 0.8, 0.1, 2.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (89, 'Grape juice', 65, 0.6, 0, 15);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (90, 'Tea', 0, 0, 0, 0.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (91, 'Coffee', 2, 0.2, 0, 0.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (92, 'Cocoa powder', 315, 21, 21.3, 45);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (93, 'Cocoa based milk drink', 68, 3.5, 1.5, 10);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (94, 'Soft drink carbonated', 24, 0, 0, 5.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (95, 'Coca-cola', 42, 0, 0, 10.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (96, 'Water', 0, 0, 0, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (97, 'Wheat flour', 345, 10.7, 1.3, 74.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (98, 'Rye flour', 335, 7.1, 1.1, 77);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (99, 'Starch', 326, 0.4, 0.1, 83.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (100, 'Dumplings with curd filling', 190.42, 11.17, 3.22, 28.38);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (101, 'Boiled curd dumplings', 148.77, 17.09, 1.18, 16.67);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (102, 'Fried curd dumplings', 262.34, 16.22, 11.94, 23.02);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (103, 'Rustic pancakes', 229.14, 10.83, 13.84, 15.88);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (104, 'Pancakes', 237.54, 8.94, 6.05, 38.28);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (105, 'Pancakes with meat filling', 317.43, 15.21, 16.17, 28.95);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (106, 'Pancakes with curd filling', 260.3, 13.02, 8.97, 32.96);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (107, 'Yeasty cakes with raisin', 284.1, 7.68, 6.92, 50.83);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (108, 'Pasta bake', 167.1, 4.4, 0.54, 27.39);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (109, 'Curd bake', 251.33, 16.67, 11.78, 20.18);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (110, 'Curd and rice bake', 160.14, 5.13, 5.62, 23.68);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (111, 'Oat flakes', 365, 13.8, 6.7, 67.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (112, 'Buckwheat groats', 349, 12.6, 3.1, 69.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (113, 'Wheat grain', 317, 11.7, 1.9, 69.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (114, 'Semolina', 360, 10.3, 1, 74.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (115, 'Pearl barley', 335, 9.8, 1.8, 75.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (116, 'Rice�', 356, 8.8, 0.4, 76.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (117, 'Rye grain', 307, 9.5, 1.7, 72.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (118, 'Millet groats', 352, 10.6, 2.9, 69.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (119, 'Grits', 144.08, 5.68, 5.75, 19.43);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (120, 'Powdery rice porridge', 141.15, 3.04, 3.05, 26.28);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (121, 'Farina pudding', 155.49, 4.37, 5.08, 24.28);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (122, 'Sour cream', 120, 3, 10, 4.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (123, 'Mayonnaise', 334, 1.2, 32.5, 8.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (124, 'Vinegar', 47, 0.6, 0.1, 9.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (125, 'Pepper black', 309, 11.8, 8.6, 63.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (126, 'Caraway', 333, 19.8, 14.5, 49.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (127, 'Bay leaf', 277, 9.4, 5.4, 71);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (128, 'Herring', 222, 20, 15.4, 0.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (129, 'Hake', 89, 17.2, 2.2, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (130, 'Carp', 123, 17.1, 6, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (131, 'Salmon', 202, 19.9, 13.6, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (132, 'Pike', 87, 19.7, 0.8, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (133, 'Cod', 75, 17.7, 0.4, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (134, 'Halibut', 124, 20.1, 4.8, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (135, 'Plaice', 93, 17.1, 2.7, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (136, 'Mackerel', 174, 18.8, 10.9, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (137, 'Pikeperch', 84, 18.7, 0.8, 0.4);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (138, 'Sprats canned in oil', 347, 15.1, 31.6, 0.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (139, 'Tuna', 136, 23.7, 4.6, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (140, 'Eel', 278, 15, 24.5, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (141, 'Brown trout', 111, 18.2, 4.2, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (142, 'Rainbow trout', 161, 18.6, 9.6, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (143, 'Chicken', 162, 19.4, 9.3, 0.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (144, 'Cheese Parmesan', 454, 41.5, 32, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (145, 'Cheese Camembert', 290, 21, 22.8, 0.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (146, 'Cheese Emmental', 383, 28.8, 29.7, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (147, 'Mustard', 167, 5.7, 6.4, 22);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (148, 'Ketchup', 112, 1.8, 0.5, 24.8);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (149, 'Tomato paste', 110, 3.9, 0.5, 23.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (150, 'White sauce', 70.91, 1.04, 5.26, 5.18);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (151, 'Garlic sauce', 60.84, 2.71, 0.23, 11.82);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (152, 'Milk sauce', 141.14, 3.16, 9.46, 11.23);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (153, 'Red sauce', 180.71, 1.94, 13.77, 12.86);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (154, 'Onion sauce', 120.98, 1.61, 5.35, 18.41);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (155, 'Butter', 660, 0.8, 72.5, 1.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (156, 'Lard', 896, 0.2, 99.5, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (157, 'Olive oil', 883, 0.1, 99.5, 0.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (158, 'Corn oil', 884, 0.1, 99.7, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (159, 'Rapeseed oil', 884, 0.1, 99.8, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (160, 'Sunflower oil', 884, 0.1, 99.8, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (161, 'Soyabean oil', 885, 0.1, 99.8, 0.1);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (162, 'Veal', 104, 19.6, 2.7, 0.3);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (163, 'Roebuck', 100, 21.8, 1.4, 0);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (164, 'Poppy seeds', 517, 19.9, 46.7, 24.7);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (165, 'Cashewnut', 585, 15.8, 46.3, 30.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (166, 'Walnut', 655, 18.5, 60.4, 14.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (167, 'Coconut', 362, 4.5, 35.3, 15.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (168, 'Coconut flakes', 615, 5.7, 63, 27);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (169, 'Hazelnut', 658, 17.6, 63.2, 14.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (170, 'Almonds', 580, 20, 52, 20.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (171, 'Pistachio nut', 610, 20.5, 48.5, 27.6);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (172, 'Sunflower seeds', 611, 22.5, 49, 21.5);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (173, 'Sesame seeds', 597, 22, 53.2, 14.9);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (174, 'Flaxseed', 414, 23.4, 31, 34);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (175, 'Peanut', 569, 19.2, 46.1, 19.2);
insert into product (id_product, product_name, kcal, protein, fat, carbohydrates) values (176, 'Ice-cream', 125, 4.2, 2.1, 18.1);
